import express from "express";
import MyRestaurantController from "../controllers/MyRestaurantController";
import { validateMyRestaurantRequest } from "../middleware/validation";
import { extractUserIdMiddleware } from "../middleware/Middleware";
const router = express.Router();
router.get("/order", extractUserIdMiddleware, MyRestaurantController.getMyRestaurantOrders);
router.patch("/order/:orderId/status", extractUserIdMiddleware, MyRestaurantController.updateOrderStatus);
router.get("/", extractUserIdMiddleware, MyRestaurantController.getMyRestaurant);
router.post("/", extractUserIdMiddleware, validateMyRestaurantRequest, MyRestaurantController.createMyRestaurant);
export default router;
